version: '3.9'

services:
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - /backup:/backup
      - db_data:/var/lib/mysql
    networks:
      - dd

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    networks:
      - dd

  backup:
    image: backup
    container_name: backup
    restart: always
    volumes:
      - /backup:/backup
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dd

networks:
  dd:
volumes:
  db_data: